version: '3.8'

services:
  backend:
    image: ${DOCKER_USER}/products-backend:v${TAG}
    restart: always
    ports:
      - "5000:5000"
    environment:
      # We combine the credentials into a single URL so the backend 
      # knows to use the 'postgresql' driver instead of defaulting to 'sqlite'
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/proddb
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=proddb
    depends_on:
      - db

  frontend:
    image: ${DOCKER_USER}/products-frontend:v${TAG}
    restart: always
    ports:
      - "8081:80"
    volumes:
      # Map your local 'mens' folder to the path Nginx expects for 'men'
      - ./frontend/mens:/usr/share/nginx/html/images/products/men
      # Map your local 'women' folder to the path Nginx expects for 'women'
      - ./frontend/women:/usr/share/nginx/html/images/products/women
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=proddb
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata_staging:
