version: '3.8'

services:
  backend:
    image: ${DOCKER_USER}/products-backend:v${TAG}
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/proddb
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=proddb
    depends_on:
      - db

  frontend:
    image: ${DOCKER_USER}/products-frontend:v${TAG}
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /home/vboxuser/products-app/frontend/mens:/usr/share/nginx/html/images/products/men
      - /home/vboxuser/products-app/frontend/women:/usr/share/nginx/html/images/products/women
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=proddb
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata_staging:
