version: '3.8'

services:
  backend:
    image: ${DOCKER_USER}/products-backend:v${TAG}
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Updated URL with prod credentials
      - DATABASE_URL=postgresql://prodadmin:prod_secure_pass@db:5432/products_production
      - DB_HOST=db
      - DB_USER=prodadmin
      - DB_PASSWORD=prod_secure_pass
      - DB_NAME=products_production
    depends_on:
      - db

  frontend:
    image: ${DOCKER_USER}/products-frontend:v${TAG}
    restart: always
    ports:
      - "80:80"
    volumes:
      - /home/vboxuser/products-app/frontend/mens:/usr/share/nginx/html/images/products/men
      - /home/vboxuser/products-app/frontend/women:/usr/share/nginx/html/images/products/women
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=prodadmin
      - POSTGRES_PASSWORD=prod_secure_pass
      - POSTGRES_DB=products_production
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata_prod:
